### ISSUE TITLE
Redis pod keeps status "pending"

### ISSUE THREAD

**Issue by Angi2412** [instana/robot-shop#54]
Hello,
I want to use the robot-shop as an autoscaling testing application for my thesis and have some trouble deploying it in Kubernetes.
I use Kubernetes from Docker Desktop and have linkerd (via script) and Prometheus (via helm) installed.
I deployed the robot-shop as described via terminal with the command: `helm install robot-shop --namespace robot-shop .`

But when I want to check the pods status via `kubectl get pods -n robot-shop` i get the following response:
```
NAME                         READY   STATUS    RESTARTS   AGE
cart-65bddd8879-rtpjg        2/2     Running   0          5m50s
catalogue-55f4558d8d-dmfw8   2/2     Running   0          5m50s
dispatch-7c97898876-jfd5r    2/2     Running   0          5m50s
mongodb-7fcc49887c-w549g     2/2     Running   0          5m49s
mysql-6fbdd859fd-j7w57       2/2     Running   0          5m50s
payment-6d69b97956-cjg7v     2/2     Running   0          5m49s
rabbitmq-86f8d8c475-hrq9q    2/2     Running   0          5m49s
ratings-57498966c6-vgqrv     2/2     Running   0          5m50s
redis-0                      0/2     Pending   0          5m50s
shipping-8454757cf6-gk5tv    2/2     Running   0          5m50s
user-7c4c4f96d4-fpbct        2/2     Running   0          5m49s
web-6589588994-ljxjk         2/2     Running   0          5m50s
```
Which tells me that the Redis container is not running.

When inspecting the pod via `kubectl describe pods redis-0 -n robot-shop` I get:
`Warning  FailedScheduling  46s (x9 over 8m41s)  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.`

 What does that mean and how can I change that?

**Comment by Angi2412** [comment]
I solved the issue by adding a `PersostentVolume` to the `redis-statefulset.yaml` and deployed the robo-shop again:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-redis-0
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

```

**Comment by braxtonj** [comment]
New to helm but trying to get the robot shop deployed to an EC2 cluster via KOPS/Helm.

Tried four different ways, am getting errors for 3 of them and the other doesn't have a redis (not sure if this is the expected behavior.. but i don't think so).  Could you share the modified redis-statefulset.yaml to set me straight @Angi2412?

**The one that ends with no redis pod** (simply your snippet and nothing else in the file)

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: docker.io/hostpath
parameters:
  type: pd-ssd
```

**The errors:**

When I add your snipped before

```
apiVersion: apps/v1
kind: StatefulSet
```

I get this error

> Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(StatefulSet): unknown field "parameters" in io.k8s.api.apps.v1.StatefulSet, ValidationError(StatefulSet): unknown field "provisioner" in io.k8s.api.apps.v1.StatefulSet]

When I add it after "StatefulSet" (ie, after storage: 1Gi) I get this error

> Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StorageClass): unknown field "spec" in io.k8s.api.storage.v1.StorageClass


When I replace StatefulSet and use the following

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: docker.io/hostpath
parameters:
  type: pd-ssd
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  serviceName: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: redis
        image: redis:4.0.6
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: data
            mountPath: /mnt/redis
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{ if not .Values.openshift }}
        storageClassName: {{ .Values.redis.storageClassName }}
        volumeMode: Filesystem
        {{ end }}
        resources:
          requests:
            storage: 1Gi
```

I get this error:

> Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StorageClass): unknown field "spec" in io.k8s.api.storage.v1.StorageClass
